controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# pages_contact:
#     path: /contact
#     controller: App\Controller\PagesController::contact

# pages_cgu:
#     path: \cgu
#     controller: App\PagesController::cgu